local ur_content = [[
-- generated by gin
local routes_table = {
    { method = 'GET',    pattern = "/api/users",     route_info = { controller = "users", action = "list" } },
    { method = 'GET',    pattern = "/api/users/:id", route_info = { controller = "users", action = "read" } },
    { method = 'PUT',    pattern = "/api/users/:id", route_info = { controller = "users", action = "update" } },
    { method = 'POST',    pattern = "/api/users/schemas",route_info = { controller = "users", action = "schemas" } },
    { method = 'DELETE', pattern = "/api/users/:id", route_info = { controller = "users", action = "delete" } },
    --
    { method = 'POST',   pattern = "/api/register",  route_info = { controller = "users", action = "create" } },
    { method = 'POST',   pattern = "/api/login",     route_info = { controller = "users", action = "login" } },
    { method = 'GET',    pattern = "/api/logout",    route_info = { controller = "users", action = "logout" } },
}

return routes_table
]]
return ur_content
