local route_content = [[
-- generated by gin
local routes_table = {
    {method='GET',pattern="/api/{{MNAME}}",route_info={ controller = "{{MNAME}}", action = "list" }},
    {method ='POST',pattern = "/api/{{MNAME}}/schemas", route_info = { controller = "{{MNAME}}", action = "schemas" } },
    {method='GET',pattern="/api/{{MNAME}}/:id",route_info={ controller = "{{MNAME}}", action = "read" }},
    {method='POST',pattern="/api/{{MNAME}}",route_info={ controller = "{{MNAME}}", action = "create" }},
    {method='PUT',pattern="/api/{{MNAME}}/:id",route_info={ controller = "{{MNAME}}", action = "update" }},
    {method='DELETE',pattern="/api/{{MNAME}}/:id",route_info={ controller = "{{MNAME}}", action = "delete" }}
}
return routes_table
]]

return route_content